### ISSUE TITLE
Application scaling issue on non-1080p displays

### ISSUE THREAD

**Issue by codernaut** [RohitAwate/Everest#11] opened 2018-05-05 03:41 UTC
GUI should reallign accroding to screen size

![image](https://user-images.githubusercontent.com/6038652/39659357-10994abe-5040-11e8-96e9-224bc682c34b.png)

**Comment by cstroe** [comment] 2018-05-05 04:10
On OS X:

<img width="1440" alt="screen shot 2018-05-04 at 11 10 16 pm" src="https://user-images.githubusercontent.com/1182093/39659556-5a6f6ff6-4ff0-11e8-876f-980d6d112874.png">

**Comment by RohitAwate** [comment] 2018-05-05 04:15
I'm quite confident that this has got something to do with the screen resolution. @codernaut and @cstroe could you share your screen resolutions? I have a fix ready, I just need to confirm that resolution is the culprit.

**Comment by cstroe** [comment] 2018-05-05 04:35
<img width="304" alt="screen shot 2018-05-04 at 11 34 53 pm" src="https://user-images.githubusercontent.com/1182093/39659691-c5af1fd4-4ff3-11e8-803f-bc2202a9b2f5.png">

**Comment by RohitAwate** [comment] 2018-05-05 05:57
[Everest-Alpha-1.0-TestBuild.zip](https://github.com/RohitAwate/Everest/files/1976371/Everest-Alpha-1.0-TestBuild.zip)
Could you try out this build and see if the issue is fixed, @codernaut and @cstroe?

**Comment by codernaut** [comment] 2018-05-05 11:04
yes, issue resolved

**Comment by HSchmale16** [comment] 2018-05-06 00:01
Please make a new release if this is fixed. I'm affected too on 1600x900.

**Comment by RohitAwate** [comment] 2018-05-06 01:09
@HSchmale16 did you try out the test build I have up above?
I'll close this issue and release a new build once you and @cstroe confirm positively.

**Comment by HSchmale16** [comment] 2018-05-06 01:16
It works now. Just tried the new build.

**Comment by cstroe** [comment] 2018-05-10 01:33
Looks good:
<img width="1440" alt="screen shot 2018-05-09 at 8 32 27 pm" src="https://user-images.githubusercontent.com/1182093/39847655-47254af2-53c8-11e8-8000-d2b177628da0.png">

**Comment by RohitAwate** [comment] 2018-05-10 06:05
@cstroe That's great! Thanks for the confirmation.
Closing this issue now.

Also, I had a request: Could you [email](mailto:rohitawate121@gmail.com) me some macOS screenshots similar to [this](https://user-images.githubusercontent.com/23148259/39441570-030b27b8-4ccc-11e8-8ae7-688398073f7a.PNG) for the README? Or if you're interested, you could open a PR and replace the screenshot under ['Why Everest?'](https://github.com/RohitAwate/Everest#why-everest) directly. I would prefer having it in a non-maximized state with a similar, wide aspect ratio. I just want to showcase Everest running on multiple platforms but I don't have a Mac at hand.
Thanks!

**Closed by RohitAwate** 2018-05-10 06:05 UTC
